### PR TITLE
Add support for extra exchanges

### LINKED ISSUE #11: Support for other exchange types.
When using rabbitMQ you can install additional plugins including the rabbitmq_consistent_hash_exchange which is built and ships with rabbitmq by default. This would be a simple change to allow the use of type = 'x-consistent-hash'. 
Documenation for the plugin can be found on the plugin github: 
https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange

Additionally an option for a session/random routing key would be a big win for this to be adopted.

### PR DESCRIPTION
**Pull request by dsolsona**
This pull requests adds support for using the RabbitMQ plugin to connect to exchanges using the consistent hash exchange (https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange) or the sharded queues exchange (https://github.com/rabbitmq/rabbitmq-sharding)

This closes #11

### CODE REVIEW

**Comment by dsolsona** [comment]
I've signed the CLA.

**Comment by dsolsona** [comment]
Hi, I've already signed the CLA I don't know why it keeps saying I haven't signed it.

**Comment by dsolsona** [comment]
Is there anyone reviewing these plugins?

**Comment by chrisboulton** [comment]
Hey @suyograo, what are the chances of getting these changes merged down? We'd very much like to avoid having a custom fork of this module just to do the above!

**Comment by markwalkom** [comment]
@andrewvc can we get this looked at please mate?

**Comment by andrewvc** [comment]
Sorry for the delays guys!

**Pull request closed without merging**
