### PR TITLE
Prefetch count fix

### PR DESCRIPTION
**Pull request by borisyukd**
Sets "prefetch_count" parameter for created channel

### CODE REVIEW

**Comment by borisyukd** [comment]
this pull also fixes  #5 issue

**Comment by andrewvc** [comment]
Thanks for adding this @borisyukd ! Can you move the config option from the rabbitmq input to here? All the logic around the prefetch should be in this module.

Also, It'd be great if you could squash your commits and force push to reduce your PR to a single request first :)

**Comment by ThomasADavis** [comment]
This almost works.  You need to add the config section the prefetch_count configuration option, and then it works.

**Comment by borisyukd** [comment]
@andrewvc and @ThomasADavis 
Thank you for advice. I just squashed my commits and PR looks much better now!

**Comment by andrewvc** [comment]
@borisyukd the last thing this needs to pass is for the specs to be fixed, since this breaks the expectations when `bundle exec rspec spec` is run.

Once the specs pass I can merge it in :)

**Comment by borisyukd** [comment]
I added some lines to spec file

**Comment by andrewvc** [comment]
Great work here @borisyukd ! Merging this in :)

**Pull request closed without merging**
